### ISSUE TITLE
Slashes are not escaped in paths

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#1003]
1. Run `inspect({a: {b: {}}, "a/b": []})`
2. Expand `a`
3. Expand `b` (inside `a`)

Result: `a/b` is also expanded.

Either escape slashes in paths, or consider using symbols instead of strings to avoid collisions.

**Comment by nchevobbe** [comment]
Node paths were refactored to use Symbols in https://github.com/devtools-html/devtools-core/pull/1013 , so we don't have path clashes anymore
