### ISSUE TITLE
Bump launchpad version

### ISSUE THREAD

**Issue by Garbee** [devtools-html/devtools-core#115]
We need to bump the launchpad version to get `yarn install` to work on Windows properly for `devtools-reps` and anything else that requires the `make-bundle.js` file.

cc @jasonLaster

**Comment by juliandescottes** [comment]
@Garbee launchpad was bumped a few times yesterday

Last version is 0.0.32, I guess we can close this. Feel free to reopen if needed.

**Comment by Garbee** [comment]
Nope, it was bumped and the reps repo updated. We just never came back to this to close.

Thank you!
