### ISSUE TITLE
Firebug theme uses different font

### ISSUE THREAD

**Issue by irfanhudda** [devtools-html/devtools-core#159]
Firebug theme uses different font. Here are screenshots for comparison

|Light|Dark|Firebug|
|-|-|-|
|![light_pause](https://cloud.githubusercontent.com/assets/1755089/22517853/8d667162-e8d0-11e6-960a-601539c12d6b.png)|![dark_pause](https://cloud.githubusercontent.com/assets/1755089/22517865/973d2ece-e8d0-11e6-8ef6-b7e4bec0cb2d.png)|![firebug_pause](https://cloud.githubusercontent.com/assets/1755089/22518022/1a8068c8-e8d1-11e6-9ca6-e076bd292a91.png)|

Notice the font in source tree and tab bar. Is this the expected behavior?

**Comment by jasonLaster** [comment]
I believe this was intentional. Is that correct @janodvarko?

**Comment by janodvarko** [comment]
Correct, Firebug uses different font.

Do note that the Debugger UI needs improvements to look more like the old Debugger with Firebug theme activate
![debugger](https://cloud.githubusercontent.com/assets/37785/22692648/3745f3ba-ed40-11e6-88de-b7e35b725c09.png)
d. I am attaching a screenshot of the old UI.

Honza

**Comment by irfanhudda** [comment]
@jasonLaster @janodvarko Thanks for clarification. I'll close this issue.
