### ISSUE TITLE
Upgrade to react 15.3.2

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#174]
We should update react to stay up to date with MC.

**Comment by wldcordeiro** [comment]
15.3.2? Not the most recent (15.4.2 as of writing.)

**Comment by juliandescottes** [comment]
When the bundle is delivered in mozilla-central, it is using the version of React in devtools/client/shared/vendor (see http://searchfox.org/mozilla-central/source/devtools/client/shared/vendor) 

For now this is 15.3.2. To avoid unexpected issues when releasing to mozilla-central, it's better if we stay synchronized.

**Comment by juliandescottes** [comment]
This is done!
