### ISSUE TITLE
nodejs 6.9 version requires off the road setup on ubuntu

### ISSUE THREAD

**Issue by ochameau** [devtools-html/devtools-core#196]
I'm using current Ubuntu release which ships with node 6.6, whereas 6.9 is required to build debugger.html.
I got that fixed by installing nodejs 6.9 via PPA:
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04#how-to-install-using-a-ppa
But that adds yet another step to give it a try.

**Comment by wldcordeiro** [comment]
Most of us use https://github.com/creationix/nvm

**Comment by julienw** [comment]
yeah, agreed, better use nvm to install node, it's a lot more convenient. Even if a kitten dies every time somebody doesn't use a package manager to install software.

**Comment by jasonLaster** [comment]
yup. we fixed the `Object.entries` dependency
