### ISSUE TITLE
[Launchpad] Tabs are being cleared 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#207]
Tabs are being cleared after a couple of seconds.

it used to re-connect to firefox every 3 seconds now, it just uses the protocol to list tabs. We're likely not updating the tab reducer correctly.

**Comment by clarkbw** [comment]
Here's what I'm seeing, this is my launchpad and when I refresh you see the tabs.  Seconds later the tab just disappears.  I can refresh again and see them but they keep disappearing. 
http://recordit.co/Hjpc5UVAsc

**Comment by irfanhudda** [comment]
I'd like to look at this.

**Comment by juliandescottes** [comment]
I think the issue is that the version of client-adapters in debugger.html yarn.lock is still 0.0.17, while the latest launchpad needs 0.0.18 :( 

Related to #197

**Comment by irfanhudda** [comment]
Thanks @juliandescottes. That seems to be the problem. [https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-client-adapters/src/firefox.js#L100](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-client-adapters/src/firefox.js#L100) was recently added.

**Comment by juliandescottes** [comment]
@irfanhudda I see devtools-client-adapters is now 0.0.19 in debugger-html yarn.lock.
Should this issue be closed ?

**Comment by clarkbw** [comment]
I'm seeing weird refreshing but the tabs are not clearing anymore so this can be closed.
