### ISSUE TITLE
[Luanchpad] Hot Reloading

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#217]
We should show something next to hot reloading to indicate it's broken. 
Also disable the button

**Comment by nchevobbe** [comment]
Agree, I spent 15 minutes wondering what mistake I did to find out it was due to hot reloading being broken :)

**Comment by wldcordeiro** [comment]
This is kind of a dupe of #195? I found info on how to fix it but just hadn't chased that yet. You're welcome to try @nchevobbe
