### ISSUE TITLE
ReactDOM 15.3 does not work with single module plugin

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#23]
react-dom has an index.js file with just a module.exports = require('react/lib/reactDOM), which our single-module-plugin turns into module.exports = require() and fails to load react dom.

**Comment by juliandescottes** [comment]
Does this mean SMP confuses the index.js from react-dom with another similar file ?
I see two options here: 
- ignore small files (kind of random but should work here)
- improve the plugin to run in several steps:
  - a: mark all the purely duplicated files (without touching require statements)
  - b: if a require() points to a duplicate marked in step a, normalize it to always point to the same ID
  - c: repeat until no more duplicates are marked

**Comment by jasonLaster** [comment]
```js
'use strict';

module.exports = require('react/lib/ReactDOM');
```

**Comment by clarkbw** [comment]
With SMP gone, is this still an issue?

**Comment by juliandescottes** [comment]
No, moreover we're already using react & react-dom 15.3 :)
