### ISSUE TITLE
[SourceMap] browserify is not working

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#246]
Source maps generated by Browserify + Exorcist don't seem to be working on Nightly.

Try the following example: [sourcemaps-bug.zip](https://github.com/devtools-html/debugger.html/files/694321/sourcemaps-bug.zip)

Note that source maps appear under the "no domain", separated from the generated bundle:

![screen shot 2017-01-09 at 19 19 16](https://cloud.githubusercontent.com/assets/63681/21777888/44ae64a2-d6a1-11e6-8975-71bb9830bb72.png)

When clicking in the console to see the source for the error, I'm taken to the source of `bundle.js` instead of the relevant source file (`main.js`).

Note: these source maps do work in Chrome, so I'm don't think it's a browserify/exorcist bug, but maybe something related to the paths

original bug: github.com/devtools-html/debugger.html/issues/1654

**Comment by tromey** [comment]
The test case works fine now.

The "no domain" text comes from the debugger.  I'll update the bug there.
