### ISSUE TITLE
[LaunchPad] Make the launchpad title configurable

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#27]
It is hardcoded to "Firefox Debugger" ATM (https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/index.html#L4), which can be a bit weird for other tool using it (like devtools-reps)

**Comment by jasonLaster** [comment]
Yup! Great point, perhaps we also want to make the favicon configurable too!

**Comment by juliandescottes** [comment]
Two small things:

1.  The inspector is not using the index.html from launchpad at the moment. Instead it sets `development.customIndex = true` in its launchpad config and defines its own route to serve "/". One option would be to say that each tool is responsible providing its own index.html and define a route for it.

2. After merging #34, the style bundle is no longer styles.css but [bundle-name].css which means that the following snippet should also be customized for each tool: 
```
{{^isDevelopment}}
<link rel="stylesheet" href="assets/build/styles.css" type="text/css" />
{{/isDevelopment}}
```
