### ISSUE TITLE
[LaunchPad] Error launching firefox with selenium

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#271]
We're seeing an issue with launching firefox that looks related to [selenium](https://github.com/SeleniumHQ/selenium/issues/2678).

> Unable to parse new session

![windows_powershell_2017-03-24_17 09 28](https://cloud.githubusercontent.com/assets/254562/24311954/cd46bd7e-10ac-11e7-9eaf-0f30080abc23.png)

It looks like the relevant versions are:

* geckodriver@^1.2.0: version "1.5.0"
* selenium-webdriver@^3.0.1:  version "3.3.0"

#### Work around

While this is broken, you can use [gcli](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md#firefox-gcli)

**Comment by bomsy** [comment]
Looks like this is fixed!
