### ISSUE TITLE
[LaunchPad] Clicking on tab title in storybook does fun stuff

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#29]
I heard you liked stories, so I put stories in stories in stories :)

![screenshot at dec 25 22-38-55](https://cloud.githubusercontent.com/assets/578107/21472981/ff5cb49e-caf2-11e6-93cf-70a0dd97c00a.png)

Eventually, it breaks the story navigation too (clicking on another story doesn't do anything)

**Comment by jasonLaster** [comment]
haha - so... we can make it do something boring, such as pass in a stub action for navigating, which would let us see the navigation in the action logger and avoid silly things :)
