### ISSUE TITLE
[LaunchPad] add bin scripts for assets

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#3]
There are two main operations `sync-assets` `publish-assets`

`sync-assets`  - when a tool wants to copy assets to a local m-c for running in the panel or tests

`publish-assets`- when a  tool wants to publish assets to a dist directory before bumping a version.

**Comment by wldcordeiro** [comment]
@jasonLaster could you elaborate as to what we want to do here? I'll take this issue.

**Comment by jasonLaster** [comment]
Sure!

But I've got it. We want copy-assets and publish-assets to move to core.

I got it bc I want to get all of this stuff hammered out and it's all in my
head lol.

**Comment by wldcordeiro** [comment]
@jasonLaster Cool cool, reassigned to you then.

**Comment by jasonLaster** [comment]
I'm going to close this as we added the scripts to reps for the time being
