### ISSUE TITLE
Support theme-switching in devtools-core

### ISSUE THREAD

**Issue by rickychien** [devtools-html/devtools-core#313]
Firefox panel has supported native theme depends on platform, we should support this feature and port theme-switching.js from m-c https://searchfox.org/mozilla-central/source/devtools/client/shared/theme-switching.js

@jasonLaster I'm curious about how debugger supports theme switching and especially for displaying different UI on different platforms?

**Comment by wldcordeiro** [comment]
@rickychien https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-launchpad/src/index.js#L30

**Comment by jasonLaster** [comment]
here are our theme [docs](https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#themes)


![](http://g.recordit.co/5ktzTek7S3.gif)
