### ISSUE TITLE
[launchpad] fix menus

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#334]
Looks like the latest patch to menus broke Menus in the launchpad's settings pane.

Lets try and get a fix in along with a unit test to prevent future regressions.

#### screenshots
|before|after|
|---|--|
|<img src='https://shipusercontent.com/6739e1f4f782ddc226bc583edef68e72/Screen%20Shot%202017-04-14%20at%203.07.29%20PM.png' title='Screen Shot 2017-04-14 at 3.07.29 PM.png' width=313>|<img src='https://shipusercontent.com/bd760850d92c827aa1cbd777a38e73ac/Screen%20Shot%202017-04-14%20at%203.07.26%20PM.png' title='Screen Shot 2017-04-14 at 3.07.26 PM.png' width=479>|

**Comment by rickychien** [comment]
Sorry for that. This could be due to
https://github.com/devtools-html/devtools-core/commit/764a083569af4681b65fb4526301a92a64ceced3#diff-5ef54ae9c99b89b342d2c02a2e0a7fecR57
