### ISSUE TITLE
Bump package request

### ISSUE THREAD

**Issue by rickychien** [devtools-html/devtools-core#349]
There are few issues have fixed in recent PRs. Netmonitor is going to lock down a stable package version.

@jasonLaster would you do me a favor for this? Thanks!

See https://bugzilla.mozilla.org/show_bug.cgi?id=1359448

**Comment by jasonLaster** [comment]
`devtools-connection` and `devtools-launchpad`have been bumped. 

I've also added @gasolin as a contributor. @rickychien happy to add you as well if you have an npm account

**Comment by rickychien** [comment]
Cool! Thanks. My npm account is rickychien and I'm also happy to become devtools-core contributor as well, please add me in :)

**Comment by rickychien** [comment]
Everything works! I'm going to close this issue. Thank your Jason.
