### ISSUE TITLE
[LaunchPad] If there's only one tab, pressing enter in the filter input should start the "tab inspection"

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#35]
The tab should have a dedicated style (with a blue background, like when we hover the tabs in the sidebar).
Maybe we could just directly focus the element (so pressing enter would work out of the box since the `onClick` would be triggered), but if we're typing in the input, it might be weird.

Or maybe we can only add proper tab indexes and some style for `:focus` to make the app easy to operate with the keyboard only.

~~This is blocked by https://github.com/devtools-html/devtools-core/pull/33~~ Update: https://github.com/devtools-html/devtools-core/pull/33 is now merged

**Comment by jasonLaster** [comment]
We can also default to selecting the first tab by default :)

**Comment by nchevobbe** [comment]
Fixed in https://github.com/devtools-html/devtools-core/pull/40
