### ISSUE TITLE
applySourceMap should notify other clients of source map service

### ISSUE THREAD

**Issue by tromey** [devtools-html/devtools-core#352]
If `applySourceMap` is called, it will modify the source map for a given resource.  However, other clients of the service have no way to be notified that this has happened.  So, for example, pretty-printing a source in the debugger will not result in console links being updated.

It's unclear to me if this should be fixed in devtools-source-map or somewhere in the toolbox.

**Comment by jasonLaster** [comment]
So, there are two potential use cases: updating and creating source maps.

Currently, `applySourceMap` is used [here] to create a new source map consumer after the debugger has created a pretty printed file. While it is possible to update a source map, it is something that we opted not to do at the moment.

We can do one of two things, if the console wants to handle the case of updating a location when the debugger prettifies a file:

* listen for new files being mapped. 
* have the debugger panel emit a "prettyPrint" event 

The first option is more generic, but might not be needed at the moment if it is just a couple cases.

[here]: https://github.com/devtools-html/debugger.html/blob/master/src/actions/sources.js#L294-L295

**Comment by tromey** [comment]
I'm thinking more along the lines of, if the debugger and other toolbox clients have to agree on sourceID cookies in order to avoid sourcemap re-fetching, then all the details should be in a service, and the service should emit the events.  So, maybe I'll move the service from https://bugzilla.mozilla.org/show_bug.cgi?id=1359144 into this package, and change the debugger to use it.  I haven't looked at the debugger part yet, though (this particular task is P2 or P3).

**Comment by tromey** [comment]
Another reason to move the service over is to have a single place listening to `will-navigate` events and clearing the source map worker's cache.  Currently this is duplicated in the debugger and the service, see https://bugzilla.mozilla.org/show_bug.cgi?id=1366062

**Comment by tromey** [comment]
I've come to think that this needs to be done in the toolbox, so I'm closing this in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1397714
