### ISSUE TITLE
[SourceMap] CNN generates a garbled source map

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#356]
1. go to CNN.com
2. observe the error in the console

the source map worker fails to fetch the map locally, the content [here] looks like [this], and should look like [this]

This is the URL networkRequest fails to fetch: http://cdn.livefyre.com/libs/Livefyre/v1.1.1/builds/325/Livefyre.min.js.map

[this]:http://cdn.livefyre.com/libs/Livefyre/v1.1.1/builds/325/Livefyre.min.js.map

[this]:https://gist.github.com/f8deaa389b1310c96561f1e95e05acbb
[here]:https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-source-map/src/source-map.js#L87

**Comment by tromey** [comment]
I tried this today.  I see livefyre.min.js in the debugger sources, but it appears to still be minified, and I'm not sure whether source maps are working at all.  I would expect to see some error in the console if they are failing.

**Comment by tromey** [comment]
The two source-map links in the original report are identical.

**Comment by tromey** [comment]
The Livefyre source map definitely exists, is read by the worker, and has a bunch of sources and `sourcesContent`.  Still investigating why these don't show up.

**Comment by tromey** [comment]
`getOriginalURLs` does return them.
