### ISSUE TITLE
launch browser button should give feedback

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/devtools-core#359]
I'm always a bit unsure if I've actually clicked the button or not.  I think we need some depressed state and a bit of animations here.

**Comment by jasonLaster** [comment]
we should also show the tabs!

this is a pending PR on the launchpad

**Comment by clarkbw** [comment]
Is that happening in #284 ?

**Comment by bomsy** [comment]
@clarkbw yeah it is. Merged now!
