### ISSUE TITLE
[LaunchPad] Add a settings pane

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#37]
Back in October, I [explored](https://github.com/devtools-html/debugger.html/issues/881) adding a settings pane, which would be easier for contributors  than editing the settings through the `local.json`.

I created this [branch](https://github.com/devtools-html/debugger.html/compare/master...jasonLaster:settings-panel?expand=1) with the backend support for reading and editing the local.json.

I think step 1 would be to add a couple simple features: 

* select theme
* toggle RTL
* toggle hot reloading

And then perhaps next we could add toggle features.

What do you guys think?

![](https://cloud.githubusercontent.com/assets/254562/19096619/d2f51e40-8a6b-11e6-9742-f8f6e0d97916.png)

**Comment by jasonLaster** [comment]
CC @jacobjzhang, interested in hacking on this?

**Comment by jacobjzhang** [comment]
@jasonLaster hell yea!

**Comment by nchevobbe** [comment]
> What do you guys think?

Definitely nice

**Comment by jasonLaster** [comment]
🚢
