### ISSUE TITLE
 Display getter function on Objects

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#397]
_Moved from https://github.com/devtools-html/reps/issues/138_

If you evaluate this in the Reps test app : 
```js
x = { y: 0 }; Object.defineProperty(x, 'y', { get: function() { return  0; } });
```
it renders as : 
- TINY `Object`
- SHORT `Object { y: Object }`
- Long `Object { y: Object }`

In the old console, this was displayed like `Object { y: Getter }` which reflect better the shape of the object.

We should do the same in Reps.
The grip we got  when evaluating  `x = { y: 0 }; Object.defineProperty(x, 'y', { get: function() { return  0; } });` is : 
```js
{
  "from": "server1.conn8.child1/consoleActor2",
  "input": "    x = { y: 0 }; Object.defineProperty(x, 'y', { get: function() { return  0; } });",
  "result": {
    "type": "object",
    "actor": "server1.conn8.child1/obj43",
    "class": "Object",
    "extensible": true,
    "frozen": false,
    "sealed": false,
    "ownPropertyLength": 1,
    "preview": {
      "kind": "Object",
      "ownProperties": {
        "y": {
          "configurable": true,
          "enumerable": true,
          "get": {
            "type": "object",
            "actor": "server1.conn8.child1/obj44",
            "class": "Function",
            "extensible": true,
            "frozen": false,
            "sealed": false,
            "displayName": "get",
            "location": {
              "url": "debugger eval code",
              "line": 1
            }
          },
          "set": {
            "type": "undefined"
          }
        }
      },
      "ownPropertiesLength": 1,
      "safeGetterValues": {}
    }
  },
  "timestamp": 1493218529771,
  "exception": null,
  "frame": null,
  "helperResult": null
}
```

This contains all the information we need to display properly that a property has a getter.

**Comment by nchevobbe** [comment]
> we are currently showing getters in the debugger. See devtools-html/debugger.html#2674

**Comment by bgrins** [comment]
This is also logged at https://bugzilla.mozilla.org/show_bug.cgi?id=1380504

**Comment by bgrins** [comment]
@jasonLaster - once getter support is added in reps can the code at https://github.com/devtools-html/debugger.html/blob/master/src/client/firefox/commands.js#L196-L199 be removed?

**Comment by jasonLaster** [comment]
Yep

**Comment by nchevobbe** [comment]
Here is how this was handled in the variable view : 

<img width="566" alt="screen shot 2017-07-17 at 17 08 19" src="https://user-images.githubusercontent.com/578107/28277718-b1ee31ea-6b12-11e7-8076-5ffb72c07403.png">

**Comment by nchevobbe** [comment]
Fixed by https://github.com/devtools-html/devtools-core/pull/511
