### ISSUE TITLE
Move Reps tests from mochitest to jest

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#415]
At the moment, we have one mochitest for each Rep.
Those mochitest don't have any real value over jest since we are only doing shallow rendering with pre-generated stubs.

Having those tests converted to jest ones would allow us to:
- run the tests faster
- do not need to have a local copy of firefox to launch tests

~Here is the list of the tests we need to migrate :~ Nothing left !

DONE: 
- [x] ~test_reps_attribute.html~ 🏅 @sidthesloth92
- [x] ~test_reps_comment-node.html~ 🏅 @jakub-c
- [x] ~test_reps_date-time.html~ 🏅 @arashm
- [x] ~test_reps_document.html~ 🏅 @arashm
- [x] ~test_reps_element-node.html~ 🏅 @arashm
- [x] ~test_reps_error.html~ 🏅 @arashm 
- [x] ~test_reps_function.html~ 🏅 @arashm 
- [x] ~test_reps_infinity.html~ 🏅 @sidthesloth92
- [x] ~test_reps_failure.html~ 🏅 @sidthesloth92
- [x] ~test_reps_long-string.html~ 🏅 @jakub-c
- [x] ~test_reps_null.html~ 🏅 @sidthesloth92
- [x] ~test_reps_number.html~ 🏅 @arashm
- [x] ~test_reps_object-with-text.html~ 🏅 @amelzer
- [x] ~test_reps_promise.html~ 🏅 @arashm
- [x] ~test_reps_regexp.html~ 🏅 @arashm
- [x] ~test_reps_string.html~ 🏅 @arashm
- [x] ~test_reps_stylesheet.html~ 🏅 @arashm
- [x] ~test_reps_symbol.html~ 🏅 @arashm
- [x] ~test_reps_undefined.html~  🏅 @iammadhan
- [x] ~test_reps_window.html~ 🏅 @arashm
- [x] ~test_reps_object-with-url.html~ 🏅 @arashm
- [x] ~test_reps_object.html~ 🏅 @arashm
- [x] ~test_reps_nan.html~
- [x] ~test_reps_text-node.html~
- [x] ~test_reps_event.html~
- [x] ~test_reps_grip-map.html~
- [x] ~test_reps_grip-array.html~
- [x] ~test_reps_array.html~
- [x] ~test_reps_grip.html~

**Comment by clarkbw** [comment]
So the [NaN](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-reps/src/test/mochitest/test_reps_nan.html) rep looks pretty simple.  Should we make an example of how to convert that one over to jest?

**Comment by nchevobbe** [comment]
@clarkbw sounds good.
In https://github.com/devtools-html/devtools-core/pull/416 I added jest for the object-inspector, let's wait until it's merged and i'll do a detailed mochitest -> jest PR for the NaN rep that will serve as an example.

**Comment by nchevobbe** [comment]
## Guide to move a Rep mochitest to a jest test:

In this guide, we will look at the NaN mochitest, which is the simplest one, and move it to a jest test.

1. Use `git mv` (so we keep the history), to move the html file from the mochitest folder to the new jest one, renaming it to a js file.

```bash
git mv packages/devtools-reps/src/test/mochitest/test_reps_nan.html packages/devtools-reps/src/reps/tests/nan.js
```

2. Replace the licence html comment with a js one
```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

```

3. Remove all the html tags, keep what is within <script> tags only

4. Remove the `window.onload = Task.async(function* () {` wrapper

5. Change the `browserRequire` to a simple `require`, with the correct path

```diff
-  const {
-    REPS,
-    getRep,
-  } = browserRequire("devtools/client/shared/components/reps/reps");
-  let { NaNRep } = REPS;
+const {
+  REPS,
+  getRep,
+} = require("../rep");
+let { NaNRep } = REPS;
```

6. Remove the upper try/catch block
```js
try {
  yield testNaN();
} catch (e) {
  ok(false, "Got an error: " + DevToolsUtils.safeErrorString(e));
} finally {
  SimpleTest.finish();
}
```

7. And for each function that was call in it, add a `describe` block

```diff
-  function testNaN() {
-    const stub = {
-      type: "NaN"
-    };
-    is(getRep(stub), NaNRep.rep, "Rep correctly selects NaN Rep");
-    const renderedComponent = renderComponent(NaNRep.rep, {object: stub});
-    is(renderedComponent.textContent, "NaN", "NaN rep has expected text content");
-  }
+  describe("test NaN", () => {
+    const stub = {
+      type: "NaN"
+    };
+    is(getRep(stub), NaNRep.rep, "Rep correctly selects NaN Rep");
+    const renderedComponent = renderComponent(NaNRep.rep, {object: stub});
+    is(renderedComponent.textContent, "NaN", "NaN rep has expected text content");
+  });

```

8. Break the function into multiple `it` blocks
```js
describe("test NaN", () => {
  const stub = {
    type: "NaN"
  };

  it("selects NaN Rep as expected", () => {
    is(getRep(stub), NaNRep.rep, "Rep correctly selects NaN Rep");
  });

  it("renders NaN Rep as expected", () => {
    const renderedComponent = renderComponent(NaNRep.rep, { object: stub });
    is(renderedComponent.textContent, "NaN", "NaN rep has expected text content");
  });
});
```

9. At this point, we have the structure that jest expects, but we are still using helper functions we wrote for mochitests (e.g. `renderComponent`). 
We should switch to use enzyme's functions to shallowly render our component and use jest assertion functions (`expect`, `toBe`, `toEqual`, ...).

```js
describe("test NaN", () => {
  const stub = stubs.get("NaN");

  it("selects NaN Rep as expected", () => {
    expect(getRep(stub)).toBe(NaNRep.rep);
  });

  it("renders NaN Rep as expected", () => {
    const renderedComponent = shallow(Rep({
      object: stub
    }));
    expect(renderedComponent.text()).toEqual("NaN");
  });
});
```

10. Add a new `nan.js` file in `packages/devtools-reps/src/reps/stubs/`
```js
let stubs = new Map([]);
stubs.set("NaN", {
  type: "NaN"
});

module.exports = stubs;
```

This is pretty simple for NaN, but other Reps might have multiple stubs.

11. You can then run `yarn test` to ensure tests are passing :)

**Comment by sidthesloth92** [comment]
Can I do Inifinity?

**Comment by nchevobbe** [comment]
@sidthesloth92 sure ! I'll mark it as taken

**Comment by Madhankumarr** [comment]
Shall I take undefined?

**Comment by arashm** [comment]
I also take Window.

**Comment by nchevobbe** [comment]
@Madhankumarr sure !

@arashm okay, thanks !

**Comment by arashm** [comment]
I do the Symbol now.

**Comment by jasonLaster** [comment]
Thanks @arashm

**Comment by arashm** [comment]
I go with StyleSheet now.

**Comment by arashm** [comment]
And now String.

**Comment by clarkbw** [comment]
Wow! Just wow!

**Comment by sidthesloth92** [comment]
I'm taking Null

**Comment by arashm** [comment]
I continue with Number.

**Comment by arashm** [comment]
I move on to Promise.

**Comment by sidthesloth92** [comment]
I'm taking Failure

**Comment by sidthesloth92** [comment]
I'm taking Array

**Comment by sidthesloth92** [comment]
I'm taking Attribute. Guess it does have the modes, so style wont' change.

**Comment by arashm** [comment]
I migrate the Document now.

**Comment by arashm** [comment]
I will work on ElementNode.

**Comment by nchevobbe** [comment]
> I migrate the ElementNode now.

Thanks @arashm . You can look at https://github.com/devtools-html/devtools-core/pull/430 to see how to deal with mouse events in this one.

**Comment by arashm** [comment]
I move on to Error.

**Comment by arashm** [comment]
I will do the Function next.

**Comment by arashm** [comment]
I'm working on the last file, Object.

**Comment by nchevobbe** [comment]
And this is __DONE__ 🎉 Thanks a lot to everyone who helped here ! @jakub-c, @sidthesloth92, @arashm, @amelzer, @iammadhan !
