### ISSUE TITLE
Arrays in TINY mode can be confusing

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#447]
_copied from [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1329162)_

STRs:

- log `[1, [2, 3]]` in the new webconsole
- the console (using reps) renders `Array [ 1, [2] ]`

The old console used to render `Array [1, Array [2]]` (same as chrome).

As I understand child items of an array are represented by reps using TINY mode. And the TINY mode for an array is `[n]` where n is the length of the represented array.

The new version felt confusing for me when I encountered it for the first time because I really read it as a javascript array "[1, [2]]". The old version can also be confusing because `Array [2]` does not universally mean "an array of length 2". I think it's marginally better than the new one because it's "the same as before" and "the same as other browsers", but it doesn't mean we can't find a better representation.

Some proposals for alternative TINY mode representations for arrays:
- `Array {n}`
- `Array |n|` (this is usually how the size of a set is represented in maths so why not?)

**Comment by nchevobbe** [comment]
Now that we have the object inspector, I wonder if having the size of an array really matters.
Let's take a new example: 
```js
console.log([1, [2, 3], [], {a: 4}, {}])
```
Let see how it is rendered at the moment:
- TINY: `▶︎ [5]`
- SHORT: `▶︎ Array [ 1, [2], [], more… ]`
- LONG: `▶︎ Array [ 1, [2], [], Object, Object ]`

I think it would be nice if we'd have something like
- TINY: `▶︎ […]`
- SHORT: `▶︎ [ 1, […], [], more… ]`
- LONG: `▶︎ [ 1, […], [], {…}, {} ]`

To be simple: arrays with at least one item would be rendered as `[…]` and empty arrays as `[]` ; and we could use the same pattern for object (`{…}` for objects with at least one property, `{}` for empty objects).

What do you think of this @juliandescottes ?

**Comment by juliandescottes** [comment]
As I said on slack, I like the proposal. 

We should make sure that when a rep logs something that is not a direct 1:1 representation of valid Javascript, it looks different (that's what I did for the error rep). I think using "…" makes it clear enough. 

Maybe we could have a slightly different style (color?) to avoid confusing the user between "…" and "..." (spread). One other tiny thing is about "…" vs "more…", maybe we should unify and have one single representation for "this has more items".

**Comment by nchevobbe** [comment]
> One other tiny thing is about "…" vs "more…", maybe we should unify and have one single representation for "this has more items".

I agree on that, it came to my mind as I was writing this. From my point of view, the ellipsis are enough to indicate there's more to see (so we'd transform `more…` to only `…`), but maybe there's some cases/culture where it's not obvious ?
We could add a title attribute on those ellipsis in order to show something more specific that those ellipsis only ("this array contains multiple elements", "this object as other properties than those shown here", etc…).

> Maybe we could have a slightly different style (color?) to avoid confusing the user between "…" and "..." (spread)

I agree on that too, maybe the ellipsis could be in a dimmed grey color (like the arrow in the object inspector ?) so they don't look like "content".

**Comment by nchevobbe** [comment]
Fixed by https://github.com/devtools-html/devtools-core/pull/508
