### ISSUE TITLE
 Make ErrorRep look more like real error

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#448]
_moved from [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1317325)_

The Rep was created with the output of the old console in mind, i.e. a simple string which describes the error and the stack, but not really actionable (except clicking on the message to open the variable view).

We could do a better job here : 
- have more error-like styling
- have collapsible stacktrace
- allow the "location" (file + line) of the trace clickable to open in the debugger

We could use the frame component we already use in the console to have proper stack trace, and have some mechanism to expand/collapse the stacktrace (by taking inspiration on how LongStringRep works maybe ? ).

**Comment by nchevobbe** [comment]
@arashm I wonder if this is something you'd be interested in ?

**Comment by nchevobbe** [comment]
That would be super nice.
Of you want to know what it is about, in Nightly you can enter this in the console (which use reps to output the data) : 
```js
let foo = () => new Error("boo")
foo()
```

Which would be rendered as : 
```
 Error: boo
Stack trace:
foo@debugger eval code:1:17
@debugger eval code:2:1
```
All in "plain text" without being able to link to the proper location (and without sourcemap support too).

Why is that ? If you look at the [grip we get when we log an error](https://github.com/devtools-html/devtools-core/blob/master/packages/devtools-reps/src/reps/stubs/error.js#L31), you can see that the `stack` property is only one big string. We just happen to put this into the Rep as is.

The idea here would be to parse this string to extract a proper stacktrace array, which would contain a structure that holds all that we need (function name, location. line and column numbers , ...) so we can output them in a nicer way.

The next step would then to be able to copy the `Stacktrace` [component we have in mozilla-central](http://searchfox.org/mozilla-central/source/devtools/client/shared/components/stack-trace.js) that would take care of the layout when we pass it the proper props. You can even see that a sourcemapService can be passed, which would then take care of the sourcemap if there are some.
I might do this (copy from m-c and put it in packages/devtools-components)


---
In order to help you see what the Rep look like when you do changes in it, you can run the test app (with `yarn start` in devtools-reps)
Hope this helps, don't hesitate to ask questions here or in Slack :)

**Comment by gregtatum** [comment]
This might not be the best place to post this, but a random thought on a weekend that I may need to re-file somewhere else. As a user, I will occasionally wrap my app in try/catch, then console.error() any errors that happen. On the side of the console it shows the line number, my expectation there is that the line would be from where the error happened if I'm logging a single error.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/1588648/27999796-7131ef16-64e6-11e7-8139-8f17c9e81ed3.png">

You can see here that it's showing index.js line 44, which is the `console.error()` call. Really want I want to know here is the source mapped location of the error itself.

**Comment by nchevobbe** [comment]
Now that we have the ObjectInspector in the console, I wonder if we couldn't use it for this purpose.

When logging an error, it would render as 
```
▼ Error: Error message
      columnNumber : 1
      fileName : "debugger eval code"
      lineNumber : 1
      message : "fuuuu"
      stack : "bad@foo.js:1:1\nerr@bar.js:"
      ▼ <stack trace>
            bad __foo.js:1:1__
            err __bar.js:1:1__
      ▶︎ __proto__ : Object
```

where foo.js and bar.js would be Frame component (hence, sourcemapped).
In the future, we might experiment with the ObjectInspector UI to be able to switch between a "custom formatted" view to a "native" one. We could use this possibility to only show the stack trace property, but still have a way to inspect the error object.
I think this is important to keep showing this as an object so people don't confuse it as an exception.

We could also take the `Window` approach for now, i.e. : 
```
▼ Error: Error message
      ▼ <stack trace>
            bad __foo.js:1:1__
            err __bar.js:1:1__
      ▶︎ [default properties]
      ▶︎ __proto__ : Object
```
So the user has a quick access to a sourcemapped stack trace but can still inspect the properties of the object.

Any thoughts on that @gregtatum ?

**Comment by nchevobbe** [comment]
> On the side of the console it shows the line number, my expectation there is that the line would be from where the error happened if I'm logging a single error.

I think this could work well. The only drawback that I see is that it wouldn't show the location where the error is logged from, but in the case of an error I wonder if showing it has any value for the user.

**Comment by gregtatum** [comment]
The window approach seems amazing! It gets to the heart of what the user wants to see.

> I think this could work well. The only drawback that I see is that it wouldn't show the location where the error is logged from, but in the case of an error I wonder if showing it has any value for the user.

It seems fine to me to hijack the `console.error()` line number to me, as we're trying to simulate logging an error. I'm not sure how the code is architected, but if you could expand the line number and show the original it would be the best of both worlds.

**Comment by nchevobbe** [comment]
Closing as we have a better plan in https://github.com/devtools-html/devtools-core/projects/3
