### ISSUE TITLE
Apply sourcemaps and formatting to the stacks on the Error rep 

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/devtools-core#452]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/1588648/27146615-c660da6c-50ee-11e7-9568-d84dd04e01f8.png">

When I throw a `console.error` at an Error object, the Error rep shows the raw text of the stack trace taken from an Error object. This stack is raw text, and does not include source maps, and we can't click into sources in that text. This gives me the impression that source maps is not working, and I can't get access to the information I need in my app.

So it seems like we should take that text, parse it, display it nicely, and spit out the sourcemapped functions and locations.

/cc @clarkbw @bgrins

**Comment by nchevobbe** [comment]
Kind of related to https://github.com/devtools-html/devtools-core/issues/448 .
We should be able to parse the error string to recreate the callstack, and then use the usual Frame component, which handle sourcemap.

**Comment by tromey** [comment]
The parsing approach won't work in all cases, because a script can be GC'd and then the source map URL won't be available.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1360252

**Comment by tromey** [comment]
You can probably ignore my earlier comment, since that's just a generic problem that doesn't impact this project any more than it does anything else.

`error.js` mentions that it can't use localization due to https://bugzilla.mozilla.org/show_bug.cgi?id=1317038.  It seems like that's likely to be a problem with moving the stack and frame components to devtools-core as well.

**Comment by nchevobbe** [comment]
The simplest way we can go right now would be to pass the [StackTrace component](https://searchfox.org/mozilla-central/source/devtools/client/shared/components/StackTrace.js) to the Reps when we create them.
In the console, it is done in the [GripMessageBodyComponent](https://searchfox.org/mozilla-central/rev/9d920555ec81f1c9d4b7fa3b08e23eb88efb60e1/devtools/client/webconsole/new-console-output/components/GripMessageBody.js#85-125).

We could then get it in the Error Rep and use it.
We'll only need to parse the `preview.stack` property to something usable for the StackTrace component.

**Comment by nchevobbe** [comment]
Closing this as we have a better plan in https://github.com/devtools-html/devtools-core/projects/3
