### ISSUE TITLE
Remove objectLink from Reps

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#468]
With the ObjectInspector coming to the console, there won't be any consumer of the `objectLink` prop we have in Reps (in the console, it's currently used to show the variable view, which would be killed when we have the object inspector).

This, I don't think there is any benefits keeping it in the code since it adds some overhead.

What do you think @janodvarko (for the DOMPanel), @jasonLaster (for the Debugger), @gabrielluong & @juliandescottes (for the Inspector).

**Comment by janodvarko** [comment]
The `objectLink` was introduced for the variable view and DOM panel doesn't use it so, removing it sound fine for me.

Honza

**Comment by nchevobbe** [comment]
Does anyone pinged here agree ? I'd like to have this removed for the new bundle that will contain the ObjectInspector

**Comment by nchevobbe** [comment]
I looked at [the code in mozilla-central](http://searchfox.org/mozilla-central/search?q=objectLink%3A&case=false&regexp=false&path=devtools%2Fclient), and it seems that only the console is using it at the moment. 
The occurence we see in the debugger bundle is because it integrates reps.

**Comment by juliandescottes** [comment]
Forgot to comment here, but yes I think it's fine from the inspector perspective, since we don't use it at the moment.
