### ISSUE TITLE
Do not use `type` in case of direct object access

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/devtools-core#480]
Reps support rendering of remote objects. In this case, values passed as `object` into Reps is always a Grip object. But, reps also support direct rendering of JS objects. In this case Reps have direct access to the JS object defined on the page.

The later scenario is used by JSONViewer. It runs directly within the page and so, has direct access to JS objects defined on the page. No grips involved.

There is one catch though, `getRep` is using `object.type` to get type of the object assuming the the `object` is always a grip. That's wrong. This means that JS objects (defined on the page) using `type` field can accidentally mangle the logic by providing random data.

Also `isGrip` method accessing `object.actor` can  cause similar troubles.

Honza

**Comment by janodvarko** [comment]
@nchevobbe: what if we introduced a new property for `Rep` called something like `noGrips` or `directAccess`. Consumers of Reps (like JSONViewer) could then pass a flag saying that JS Objects are directly consumed.

```
return Rep({
  cropLimit: 50,
  directAccess: true,
}));
```

The `getRep` method would consequently checked that flag (passed it also to `isGrip`)  and not access `type` and `actor` properties in case when `directAccess == true`.

Or if we had unified way how Grip objects are instantiated, we could do the checking automatically (e.g. `object instanceof Grip`), this would be a lot cleaner but not sure if feasible.

Honza

**Comment by nchevobbe** [comment]
It sounds like a good idea indeed.
Not sure about the name of those for now, but I can't find anything better :)

**Comment by nchevobbe** [comment]
I'll work on this so it will be in the next reps bundle (with OI) so you can fix the bug you have on the JSONViewer

**Comment by janodvarko** [comment]
Great, thanks.
Honza
