### ISSUE TITLE
Find a better way to represent empty strings

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#490]
__From https://bugzilla.mozilla.org/show_bug.cgi?id=1375752__

---

If you try to render an empty string Rep (`""`), and have `useQuotes = false`, the Rep will render `<span class="objectBox objectBox-string"></span>`, i.e. an empty element.

This might be weird in some cases (e.g. `console.log` which pass `useQuotes = false` to render its arguments).
~It shouldn't hurt to always show the quotes if the string is empty, no matter what the value of `useQuotes` is, but maybe I'm missing something ?~

Let's think about better way to display empty strings.

**Comment by Loirooriol** [comment]
How are you going to distinguish `console.log('""')` from `console.log('')`?

String quotes should have another color different than `--string-color`.

**Comment by nchevobbe** [comment]
Good point. @bwinton was suggesting having some styling to tackle this issue.

**Comment by bwinton** [comment]
A quick example: https://drive.google.com/file/d/0B8P86wwg0hsfTm9zZ2tQWFhkcjg/view 😄
(It's about a 3 line CSS change… 😉)

**Comment by bgrins** [comment]
> A quick example: https://drive.google.com/file/d/0B8P86wwg0hsfTm9zZ2tQWFhkcjg/view 😄
> (It's about a 3 line CSS change… 😉)

Even apart from the empty string situation, I like this more than the current hover state where we highlight the entire message node

**Comment by nchevobbe** [comment]
We could also use the `∅` char with some styling and a title attribute stating it's an empty string.

**Comment by nchevobbe** [comment]
`console.log("", 42)` only renders an element for 42

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6146
