### ISSUE TITLE
Add ability to edit properties in OI

### ISSUE THREAD

**Issue by bgrins** [devtools-html/devtools-core#500]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1380502.

When you double click on a property value in the OI, it could convert into a textbox and let you edit the property value, as in the variables view

**Comment by nchevobbe** [comment]
@kootoopas hey, I see you are interrested in this. Do you want me to assign the issue to you (we don't have /claim support here for now)

**Comment by jasonLaster** [comment]
@bgrins @nchevobbe I'd like to discuss some of the UX here. 

I found the old debugger variable view ux confusing at times.

**Comment by kootoopas** [comment]
@nchevobbe I'm eager to implement once the UX decisions are resolved! :)

**Comment by nchevobbe** [comment]
FYI, I find this feature very confusing as well :D We do definitely need to discuss about it

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6144
