### ISSUE TITLE
Style non-enumerable/non-writables properties in the ObjectInspector

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#506]
In the VariableView, there was a lock at the end of the line, which has a title stating if the property was not enumerable/writable/configurable/extensible. It would be nice to have something like that in the ObjectInspector.

We should not blindly copy the original behavior, maybe we can do something better for this ?

**Comment by jasonLaster** [comment]
Yeah - I think the lock is a bit much, especially because the right most column could be useful later.

I'd prefer something softer and perhaps a different hover behavior.

**Comment by Loirooriol** [comment]
You could show a pencil if it's writable/configurable. Clicking the pencil would show a textbox to edit the value (#500). The lack of a pencil would mean it's not writable/configurable.

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6142
