### ISSUE TITLE
Users should be able to copy values

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#507]
It is currently difficult to copy an object inspector's value.

1. the value does not have any user-select behavior
2. the context menu does not show copy

* I think we should support text selection when it is a text value like string, number.
* we should support copy to temporary variable
  * It might be nice to explore copying a temporary variable when the user clicks on a non-serializable object...

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6141
