### ISSUE TITLE
Add a way to evaluate getter properties

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#510]
When https://github.com/devtools-html/devtools-core/issues/397 , we'll be able to show getters and setters in Reps/ObjectInspector.
It would be nice if we could provide a way for the user to quickly evaluate a property directly in-place in the ObjectInspector.

We could show a button, with a title warning the user of potential side-effects. This button would be shown only in ObjectInspector nodes (i.e. not for the roots).

Here's a rough first approach of what it could look like : 

<img width="573" alt="screen shot 2017-07-19 at 11 25 37" src="https://user-images.githubusercontent.com/578107/28364151-3a64fba8-6c7b-11e7-9975-717a48c7614a.png">

---

On the technical side, I am not sure how to handle this for now (that's why I don't include it in #397 since it's a nice-to-have, not a critical feature).
At the moment, we don't have any actor reference for this property. We have them for the getter and the setter though, so maybe there's a way to fire the function with that reference (really not sure about this).
We may have to pass the parent reference and the property name to the new `Accessor` rep so we could evaluate the property.

**Comment by Loirooriol** [comment]
What if the getter is in the prototype chain? Some class getters expect the receiver to be an instance, not the `prototype` where they are defined.

**Comment by davidboom95** [comment]
Any news on this feature?

**Comment by wyatt8740** [comment]
Just going to chip in and point out that Firebug can do this in older versions of Firefox and in Seamonkey.

**Comment by jasonLaster** [comment]
This is something that has come up in the debugger as well. I might be able to get to it in 3-6 weeks.

I'd be happy to mentor somebody who is interested in doing it sooner :)
We're all on slack [here](https://devtools-html-slack.herokuapp.com/)

**Comment by Loirooriol** [comment]
How does Firebug determine the receiver? Does it always use the object that owns the getter?

**Comment by Loirooriol** [comment]
@wyatt8740 Yes, but a getter can be called passing an arbitrary object as the receiver (usually it's either the object that owns the getter or an object that inherits it).

For example, consider

```
var obj1 = {get foo(){return this.hasOwnProperty("foo")}};
var obj2 = Object.create(obj1);
obj1.foo; // true
obj2.foo; // false
```

So what happens if I log `obj2`, I inspect its `__proto__` (`obj1`) and then I click the button to evaluate the getter? Should it be called on `obj1` or `obj2`?

```
▼ {}                                   // obj2
│ ▼ __proto__: {…}                     // obj1
│ │ ▼ foo: Getter
│ │ │ ▶ <get>: function foo() [ ⟶ ]  // evaluate with which receiver?
│ │ ▶ __proto__: Object {…}
```

I guess I would do something like

1. Let *obj* be the object that owns the getter
2. While *obj* is not the root object in the object inspector, do
   1. Let *parent* be the parent of *obj* in the object inspector
   2. Let *prop* be the property of *parent* that contains *obj*
   3. If *prop* is not `__proto__`, break the loop.
   4. Let *obj* be *parent*
3. Evaluate the getter using *obj*  as the receiver.

Of course when I say `__proto__` I refer to the [[Prototype]], which should have an unique name. When will #651 be fixed?

**Comment by inoyakaigor** [comment]
@Loirooriol 
>  Should it be called on obj1 or obj2?
I checked behavior in Chrome and IE/Edge dev tools for this code:

```javascript
var a = {
  property: 1,
  get prop() {return this.property},
  set prop(val) {this.property = val * 2}
}
b = {}
b.__proto__ = a
```
Chrome called on `obj1`. IEdge called on `obj2`.
I think IEdge way is better. This provides more opportunities for inspect

**Comment by Loirooriol** [comment]
@inoyakaigor Not sure what your example is supposed to test, so I will use this one:

```js
var obj = {get foo(){return this.hasOwnProperty("foo")}};
Object.create(obj);
```

Chrome does not invoke unsafe getters by default, but you can click `(...)` to do so. The getter appears both in the owner and inheritor and you can invoke them independently, but the inheritor is always used as the receiver.

![chrome](https://user-images.githubusercontent.com/7477678/37556829-abf57dd6-29fb-11e8-89dc-2aff227b4742.png)

Edge invokes unsafe getters by default. The getter appears both in the owner and inheritor, using the respective object as the receiver.

![edge](https://user-images.githubusercontent.com/7477678/37556843-f0f3e0f8-29fb-11e8-9f4f-6093cf6ba580.png)

Firefox does not invoke unsafe getters by default, and does not provide any way to do so (yet). The getter appears only in the owner object.

![firefox](https://user-images.githubusercontent.com/7477678/37556896-ccb036be-29fc-11e8-980e-faeba06526f8.png)

So I think the question is: should Firefox show inherited unsafe getters in the object inspector?

 - If so, then I think it makes sense to use the object where the user invokes the getter as the receiver.
 - If not, I think the common case will be that the getter will only appear in a prototype object, and it would expect to be called on a instance. So I would follow the `__proto__` chain in the object inspector and use the outermost object as the receiver.

**Comment by inoyakaigor** [comment]
@Loirooriol I think yes, it should

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6140
