### ISSUE TITLE
Turn URLs in strings into links

### ISSUE THREAD

**Issue by bgrins** [devtools-html/devtools-core#528]
For https://bugzilla.mozilla.org/show_bug.cgi?id=1307931 we want to allow people to open links from the console. I believe we'll need to detect URLs, style them differently, and then fire a callback on click and let the toolbox actually open the link.

**Comment by nchevobbe** [comment]
Here's how it is done in the old console frontend http://searchfox.org/mozilla-central/source/devtools/client/webconsole/console-output.js#2102-2140

**Comment by nchevobbe** [comment]
Fixed by https://github.com/devtools-html/devtools-core/pull/549
