### ISSUE TITLE
Render a simplified representation when node is expanded

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#534]
This is mainly for tools that uses the OI in non TINY mode (e.g. the Console).

When collapsed, it makes sense that a node has the mode that the consumer defined.
But when the object is expanded, we could switch to TINY mode since we have duplicated information (in the preview and in the tree).

So you'd go from : 
```
▶︎ Array [1,2,3,4,5,6,7,8,9, …]
```
to
```
▼ […]
    0: 1
    1: 2
…
```

This test case is pretty simple and compact, but if the array contained longer items, it could be nicer.

**Comment by Loirooriol** [comment]
I think it makes more sense to keep the class, i.e

```
▶ Array [1,2,3,4,5,6,7,8,9, …]
```
to
```
▼ Array
    0: 1
    1: 2
    …
````
or
```
▼ Array [
    0: 1
    1: 2
    …
  ]
````

**Comment by nchevobbe** [comment]
this is fixed
