### ISSUE TITLE
[object-inspector] Expanding a large TypedArray hangs and presents a long running script warning

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#538]
Expanding an array results in a tree of ranges so that we don't try to display tens of thousands of items all at once, but we don't make the same optimization for any TypedArray types, which will often be large if they exist.

**Comment by nchevobbe** [comment]
The bucketing part should be fixed in https://github.com/devtools-html/devtools-core/issues/496.
Is there more to do here ?

**Comment by jasonLaster** [comment]
Lgtm
