### ISSUE TITLE
change privileged network request not to use cache

### ISSUE THREAD

**Issue by tromey** [devtools-html/devtools-core#551]
The code in `packages/devtools-utils/src/privileged-network-request.js` has a FIXME for not using the cache.  It would be good to fix this for source map fetching.  Currently one can wind up using a stale source map due to the cache.

One possible approach might be to change the code to use `fetch`.  Though, if doing this, we might as well just remove this code and implement it directly in `network-request.js`.

**Comment by jasonLaster** [comment]
I think the problem with fetch is CORS

**Comment by tromey** [comment]
I decided to leave the privileged code in place, because I think I don't want the timeout handling there.

**Comment by tromey** [comment]
I can land a cross-domain test in M-C to make sure that continues to work.  I suppose the idea is that the DevTools should not require CORS headers but should instead be free to fetch sources no matter where they appear?

**Comment by tromey** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1387473
