### ISSUE TITLE
Improve array preview

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#566]
Based on a discussion with @julienw , it seems that we can do a better job at previewing arrays in Reps.

Basically it would help if one could quickly see how big an array is (either by showing it in the preview, or in a tooltip).

---

Test case: `Array(1000).fill({a: 1})`
Actual results: `Array [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]`
Expected results: To be determined

**Comment by julienw** [comment]
as a first (easy ?) step I think this is worth showing the length, either explicitely (chrome shows as a prefix) or implicitely (replacing the last `...` by `and XXX more`).

**Comment by kootoopas** [comment]
@nchevobbe I'm currently working on this feature. Got the functionality down and I'm updating the `grip*` tests to be in sync with the length title postfix.

<img width="365" alt="screen shot 2017-12-15 at 2 53 01 pm" src="https://user-images.githubusercontent.com/601001/34049784-5669c20a-e1c1-11e7-9759-1d5554ac6fc9.png">

**Comment by jasonLaster** [comment]
Nice @kootoopas!

**Comment by nchevobbe** [comment]
this landed in #881
