### ISSUE TITLE
Do not include non-numerical properties in buckets

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#569]
Steps to reproduce:
Evaluate the following in the console/Reps repl
```js
x = Array.from({length: 101}).map((_, i) => i); 
x.customProp = "custom"; 
x;
```

Expected results:
There are 2 buckets with numerical properties (`[0..99]` and `[100..101]`) and 3 other nodes for non-numerical properties (`proto`, `length` and `customProp`).

Actual results:
`length` and `customProp` are in the last bucket, and the last bucket label is wrong.
<img width="260" alt="screen shot 2017-08-08 at 12 06 27" src="https://user-images.githubusercontent.com/578107/29067225-2404633c-7c32-11e7-97bf-584da71e5cf7.png">

**Comment by nchevobbe** [comment]
This patch should makes the following test pass : 

```js
  it("does not include non-numerical node in buckets", () => {
    let objProps = { ownProperties: {}, prototype: {} };
    for (let i = 0; i <= 102; i++) {
      objProps.ownProperties[i] = { value: {} };
    }
    objProps.ownProperties.length = { value: 103 };
    objProps.ownProperties.customProperty = { value: "custom" };

    const nodes = makeNodesForProperties(objProps, root);
    const names = nodes.map(n => n.name);
    const paths = nodes.map(n => n.path);

    expect(names).toEqual([
      "[0…99]",
      "[100…102]",
      "customProperty",
      "length",
      "__proto__"
    ]);

    expect(paths).toEqual([
      `root/${SAFE_PATH_PREFIX}bucket_0-99`,
      `root/${SAFE_PATH_PREFIX}bucket_100-199`,
      `root/customProperty`,
      `root/length`,
      "root/__proto__"
    ]);
  });

**Comment by Loirooriol** [comment]
I also noticed this problem. However, I think that non-index properties do need buckets when there are lots of them, e.g.

```js
new Array(1e5).fill().reduce((o,v,k)=>Object.assign(o,{[k+'a']:v}),{})
```

What I would do is separating index properties from non-index ones. If there are more than 100 indices, place them in buckets. If there are more than 100 non-indices, place them in buckets (with appropriate labels). No bucket should simultaneously have indices and non-indices.

**Comment by nchevobbe** [comment]
done
