### ISSUE TITLE
Improve the launchpad sidebar

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#604]
It would be great if the launchpad sidebar got some love

* the title included launchpad and the rocket
* settings was visually separated from the other tabs so that it is more obvious

I started the work here and got stuck

https://github.com/devtools-html/devtools-core/compare/master...jasonLaster:launchpad-sidebar?expand=1

<img src='https://shipusercontent.com/47adab20f9cc6ee6485ba2e657d070b7/Screen%20Shot%202017-08-17%20at%2012.36.45%20PM.png' title='Screen Shot 2017-08-17 at 12.36.45 PM.png' width=586>

**Comment by Ronsho** [comment]
On it.

**Comment by connorholyday** [comment]
It looks like this has been worked on, is there anything further that needs doing?

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/4559119/43223164-1cdc7414-904a-11e8-8008-c3586e875579.png">
