### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#61]
- [x] Add basic CI https://github.com/devtools-html/devtools-core/pull/60
- [x] Add flow to CI
- [x] Add debugger mochitests #8

**Comment by clarkbw** [comment]
> Add flow to CI

Probably as simple as adding `- yarn run flow` to the post test area once #60 lands

**Comment by jasonLaster** [comment]
Hmm is flow defined in client-adapters or core?

**Comment by clarkbw** [comment]
Oh right, just client-adapters for now.

**Comment by clarkbw** [comment]
With #181 merged we can easily add flow to CI now

**Comment by clarkbw** [comment]
> we can easily add flow to CI now

already there!

**Comment by nchevobbe** [comment]
Debugger mochitests are run on debugger repo, so it looks likie we can close this issue :)
