### ISSUE TITLE
LaunchPad should sync tabs

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#64]
It would be nice for the launch pad to check every second or so for new tabs on the open browsers. 

Here's a [patch](https://gist.github.com/854a5f3a2f0db707522c830ea906ab27) to help get started

```bash
curl https://gist.githubusercontent.com/jasonLaster/854a5f3a2f0db707522c830ea906ab27/raw/3cbeec0d10a15147ca3562479e2f21ea5f653b5b/foo.diff | git apply
```

**Comment by bomsy** [comment]
@wldcordeiro Are you still looking into this?

**Comment by bomsy** [comment]
This should be fixed!
