### ISSUE TITLE
Get rid of __proto__ magic

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#651]
Reps is messing with `__proto__` properties. See e.g. [bug 1390027](https://bugzilla.mozilla.org/show_bug.cgi?id=1390027) and [bug 1397772](https://bugzilla.mozilla.org/show_bug.cgi?id=1397772).

 - Stop ignoring `__proto__` enumerable own properties in object previews.
 - Stop ignoring `__proto__` own properties in object inspector.
 - Stop adding misleading `__proto__` own properties in object inspector. To reference the [[Prototype]] use a `<prototype>` property or something like that.

**Comment by nchevobbe** [comment]
See similar concerns in https://bugzilla.mozilla.org/show_bug.cgi?id=866334

**Comment by Loirooriol** [comment]
Fixed by #987 and #982. Also see #1000.
