### ISSUE TITLE
Simplify function name

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#655]
It would be nice if we could format the function names so that the long display names are cleaned up. In the screenshot below, you'll see that thunk and some other names are long.

I've attached our test cases below so you can see what the cleanup will look like. 

This change will likely be in Reps / Function and in my opinion should be for all sizes as you don't get much value out of the more specific names.

![Screen Shot 2017-09-06 at 3.43.29 PM.png](https://shipusercontent.com/eb6de458efbb85705fc393364a916fec/Screen%20Shot%202017-09-06%20at%203.43.29%20PM.png)

https://github.com/devtools-html/debugger.html/blob/master/src/utils/frame.js#L209-L230

```
const cases = {
  defaultCase: [["define", "define"]],

  objectProperty: [
    ["z.foz", "foz"],
    ["z.foz/baz", "baz"],
    ["z.foz/baz/y.bay", "bay"],
    ["outer/x.fox.bax.nx", "nx"],
    ["outer/fow.baw", "baw"],
    ["fromYUI._attach", "_attach"],
    ["Y.ClassNameManager</getClassName", "getClassName"],
    ["orion.textview.TextView</addHandler", "addHandler"],
    ["this.eventPool_.createObject", "createObject"]
  ],

  arrayProperty: [
    ["this.eventPool_[createObject]", "createObject"],
    ["jQuery.each(^)/jQuery.fn[o]", "o"],
    ["viewport[get+D]", "get+D"],
    ["arr[0]", "0"]
  ],

  functionProperty: [
    ["fromYUI._attach/<.", "_attach"],
    ["Y.ClassNameManager<", "ClassNameManager"],
    ["fromExtJS.setVisible/cb<", "cb"],
    ["fromDojo.registerWin/<", "registerWin"]
  ],

  annonymousProperty: [["jQuery.each(^)", "each"]]
};
```

**Comment by nchevobbe** [comment]
Looks nice.
I will have a PR on that shortly.
The only thing is that it changes how we display getter/setter : 
```diff
 ▼ x: Getter & Setter
-|  ▶︎ <get>: function get x()
-|  ▶︎ <set>: function set x()"
+|  ▶︎ <get>: function x()
+|  ▶︎ <set>: function x()
```
But this might be safe since we already have the `<get>` and `<set>` names ?

**Comment by jasonLaster** [comment]
actually i assume it would follow class conventions:

```diff
 ▼ x: Getter & Setter
-|  ▶︎ <get>: function get x()
-|  ▶︎ <set>: function set x()
+|  ▶︎ get x()
+|  ▶︎ set x()
```

**Comment by nchevobbe** [comment]
done
