### ISSUE TITLE
Tree component is slowing down console resize significantly

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/devtools-core#679]
STRs:
- open the console
- run `for (var i=0; i<300 ; i++) {console.log({})}`
- try to resize the console's parent window

=> The resize is extremely laggy.

See the profile at https://perfht.ml/2wfMYqZ

![console-resize](https://user-images.githubusercontent.com/1141550/30492167-e5bf1424-9a3f-11e7-9bf5-3434429c5746.gif)

(sorry about the artifacts in the GIF)

**Comment by juliandescottes** [comment]
For the record, even after removing the resize listener from the Tree component, the performance remains pretty bad. The profile doesn't show anything in JS though: https://perfht.ml/2whftoe

**Comment by nchevobbe** [comment]
fixed
