### ISSUE TITLE
DomException do not show the error message

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#682]
Steps to reproduce:
- Open the Reps repl or the console
- Evaluate 
```js
  try {
    var foo = document.querySelector("foo;()bar!");
  } catch (ex) {
    ex;
  }
```

Expected results:
It displays `DOMException: SyntaxError: "'foo;()bar!' is not a valid selector"`

Actual results:
It only shows `DOMException {  }`, and you have to expand the object to see the message

**Comment by gregtatum** [comment]
Adding myself to this to maybe take in the future @gregtatum
