### ISSUE TITLE
CSSRules are rendered as strings

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#684]
Steps to reproduce:
1. Open the Reps repl or the console
2. Evaluate `document.styleSheets`

Expected results: 
Rules are shown like : 
```
▶︎ cssRules: [CSSStyleRule, …]
```

Actual results:
Only the rule string is shown, which is weird, because it might make the user think that they are dealing with an array of strings
```
▶︎ cssRules: ["body"]
```

**Comment by gregtatum** [comment]
Adding myself to this to maybe take in the future @gregtatum

**Comment by bgrins** [comment]
Updated STR:

execute: `document.styleSheets[0].cssRules`

**Comment by weilonge** [comment]
I would like to take this issue. Can someone help me?

**Comment by nchevobbe** [comment]
Sure !
