### ISSUE TITLE
Properties on string object are not shown

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#685]
**Steps to reproduce:**
- Open the reps repl or the console
- Evaluate : 
```js
var s = new String('hello'); 
s.whatever = 23;
s;
```

**Expected results (at least that was what we had in the old console):**
The variable is rendered as `String { "hello", whatever: 23 }`

**Actual results:** 
The variable is rendered as `String { "hello" }` (but you can still see the `whatever` property when you expand the object)

---

I'm not sure about this one though. It feel weird to me like it was done in the old console, but maybe it's more "correct".

**Comment by Loirooriol** [comment]
And also for boolean and number objects:

    Object.assign(Object(true), {a:1}); // Boolean { true, a: 1 }
    Object.assign(Object(0), {a:1}); // Number { 0, a: 1 }

And symbol objects should be unwrapped ([bug 1391274](https://bugzilla.mozilla.org/show_bug.cgi?id=1391274)):

    Object.assign(Object(Symbol("s")), {a:1}); // Symbol { "s", a: 1 }

**Comment by tromey** [comment]
> It feel weird to me like it was done in the old console, but maybe it's more "correct".

My reasoning here was that it is precisely these weird cases that you're more likely to want to see while debugging.

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6131
