### ISSUE TITLE
Proxies should not have a `__proto__` node

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#687]
We do show prototype for Proxies, but we shouldn't.
Here is where we decide to load a prototype or not: https://github.com/devtools-html/devtools-core/blob/b9616604b90565680292f4ff3bfe2565ad415b17/packages/devtools-reps/src/object-inspector/utils/node.js#L809  

cc @Loirooriol

**Comment by Loirooriol** [comment]
Potentially problematic objects for getting the prototype:

 - Proxy objects: the `getPrototypeOf` trap runs. They should be blacklisted.
 - Inaccessible objects (see [bug 1394559](https://bugzilla.mozilla.org/show_bug.cgi?id=1394559)): they return `null` without problems in most cases, but the underlying object could be a same-origin proxy in an invisibleToDebugger global. Then the trap would run. So they should be blacklisted like proxies.
 - DeadObject objects: seem to return `null` without problems.
 - Opaque objects: seem to return `Object.prototype` (the one of the realm of the underlying object, with Xrays) without problems. Should not be blacklisted.
 - ...?

Potentially problematic objects for getting properties:

 - Proxy objects: some trap runs. They should be blacklisted.
 - Inaccessible objects (see [bug 1394559](https://bugzilla.mozilla.org/show_bug.cgi?id=1394559)): they throw in most cases, and can run proxy traps in the others. So they should be blacklisted like proxies.
 - DeadObject objects: they throw. Should be blacklisted or wrapped in a try statement.
 - Opaque objects: properties may exist and are retrieved without problems (from the Xray wrapper, not the underlying object). Should not be blacklisted.
 - ...?

I'm not much sure if the blacklisting should happen by modifying object.js methods or by making the object inspector not call these methods. If VariablesView is not going to be removed I guess object.js should be modified.

**Comment by nchevobbe** [comment]
we don't show it anymore
