### ISSUE TITLE
Fix keyboard navigation scrolling in the Tree component

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#690]
The Tree component relies on the `itemHeight` prop to handle scroll on keyboard navigation.
In some cases, the item height is unpredictable (for example in the ObjectInspector), so the navigation is probably broken.

What should be done is when focusing a node, checking if it is off-canvas, and if so, call `scrollIntoView` with the correct argument to scroll it at the top or the bottom of the screen.

**Comment by jasonLaster** [comment]
Lets also make sure that this works in chrome too, which might not have this function.

**Comment by nchevobbe** [comment]
Chrome seems alright with `scrollIntoView`: https://caniuse.com/#feat=scrollintoview

**Comment by nchevobbe** [comment]
This should work now
