### ISSUE TITLE
aria-activedescendant in tree must have an ID ref to the actual tree node.

### ISSUE THREAD

**Issue by yzen** [devtools-html/devtools-core#695]
aria-activedescendant attribute (on tree container) is currently not used correctly. It must point to an idref of an element that is considered active (tree node). It is set however the id attribute is never assigned when tree node is rendered. 
More examples here:
https://www.w3.org/WAI/GL/wiki/Using_aria-activedescendant_to_allow_changes_in_focus_within_widgets_to_be_communicated_to_Assistive_Technology
Working implementation in tree.js in m-c devtools:
https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/tree.js#599,650,751

**Comment by nchevobbe** [comment]
Fixed by https://github.com/devtools-html/devtools-core/pull/697
