### ISSUE TITLE
ObjectInspector fails to retrieve object properties in object with `length` property

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#707]
Steps to reproduce: 
1. Open the console or the Reps repl
2. Evaluate `({a: 1, length: 2})`
3. Expand the result object

Expected results:
The object renders as : 
```
▼ {…}
    a: 1
    length: 2
   ▶︎ __proto__: Object { … }
```

Actual results:
The object renders as : 
```
▼ {…}
   ▶︎ __proto__: Object { … }
```
i.e. without any properties

---

This is because we call the `enumProperties` function on the server with the `ignoreIndexedProperties` options, which ends up here: http://searchfox.org/mozilla-central/source/devtools/server/actors/object.js#902-903,920-921
Here the server strips every properties whose index is < `length`. In that case, since we only have 2 properties, they are both stripped from the array, so we get nothing.

The variable view did not pass the `ignoreIndexedProperties` if the object [was not an array](http://searchfox.org/mozilla-central/source/devtools/client/shared/widgets/VariablesViewController.jsm#258-259,276,292).

**Comment by Loirooriol** [comment]
> The variable view did not pass the `ignoreIndexedProperties` if the object was not an array.

Limiting `ignoreIndexedProperties` to arrays does not solve the problem, because arrays can be sparse:

    Object.assign(Array(2), {a:1})

**Comment by nchevobbe** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1403065 on bugzilla to fix enumProperties with options.
Not sure how to fix this yet without regressing performance, so I'm going to push a small fix in ObjectInspector to only adds these options for ArrayLike objects, and then we'll fix it for sparse arrays too.

**Comment by nchevobbe** [comment]
Fixed for the expanded part
