### ISSUE TITLE
ObjectInspector should show wrapped primitive

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#708]
Run `inspect(Object(123))`. Result:

    ▼ Number
      ▶︎ __proto__: Number { 0 }

It would be useful to show the `123`, e.g.

    ▼ Number
        <primitive>: 123
      ▶︎ __proto__: Number { 0 }

And analogous for boolean, string and symbol objects. The grip of the primitive value is exposed in the `wrappedValue` property of the preview.

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6129
