### ISSUE TITLE
[SYNC] devtools/client/shared/components/tree

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#710]
Looks like `tree.js` has [diverged][diff] from MC :frowning:

* [`devtools/client/shared/components/tree.js`][mc] -- [history][mc-history] --  [searchFox][fox]
* [`devtools-components/src/tree.js`][core] -- [history][core-history]

[core]:https://github.com/mozilla/gecko/blob/central/devtools-components/src/tree.js
[mc]:https://github.com/devtools-html/devtools-core/blob/master/packages//devtools/client/shared/components/tree.js
[diff]:https://gist.github.com/0d464903a9d519cccec18ab4d4050dad
[fox]:https://searchfox.org/mozilla-central/source//devtools/client/shared/components/tree.js
[core-history]:https://github.com/devtools-html/devtools-core/commits/master/packages/devtools-components/src/tree.js
[mc-history]:https://github.com/mozilla/gecko/commits/central/devtools/client/shared/components/tree.js

**Comment by nchevobbe** [comment]
I think they have different purpose for now. The tree from devtools-core needs to support variable height nodes.
Maybe when we have a suitable solution for virtualization on core we can merge it back into mc ?

**Comment by nchevobbe** [comment]
let's close this
