### ISSUE TITLE
sync task.js w/ mc

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#713]
Looks like, `task.js` has [diverged][diff] from MC :frowning:

* [`devtools/shared/task.js`][mc] -- [history][mc-history] --  [searchFox][fox]
* [`devtools-modules/src/utils/task.js`][core] -- [history][core-history]

[core]:https://github.com/mozilla/gecko/blob/central/devtools-modules/src/utils/task.js
[mc]:https://github.com/devtools-html/devtools-core/blob/master/packages//devtools/shared/task.js
[diff]:https://gist.github.com/8de8355695ae8bcb2174c6a92381fb3a
[fox]:https://searchfox.org/mozilla-central/source//devtools/shared/task.js
[core-history]:https://github.com/devtools-html/devtools-core/commits/master/packages/devtools-modules/src/utils/task.js
[mc-history]:https://github.com/mozilla/gecko/commits/central/devtools/shared/task.js

**Comment by nchevobbe** [comment]
task.js was removed by Alex in m-c. I guess we can close this or repurpose it to remove task.js here
