### ISSUE TITLE
Poor performance of the Tree on during scrolling

### ISSUE THREAD

**Issue by yurydelendik** [devtools-html/devtools-core#731]
STR:
1. Open and debug https://yurydelendik.github.io/old-man-sandbox/create-30k/f3k.html
2. Open source tree and scroll it up and down

Actual result:
CPU usage jumps to 100%

Expected result:
Scrolling of relatively static content shall not consume that much power.

Performance shows that _onScroll handling in the Tree component spends 100ms per scroll tick:
<img width="1268" alt="screen shot 2017-09-29 at 12 58 27 pm" src="https://user-images.githubusercontent.com/1523410/31029220-8b6b961e-a516-11e7-9b11-7713ed4d91a8.png">

See also https://github.com/devtools-html/debugger.html/issues/4168

**Comment by nchevobbe** [comment]
This should be fixed in the latest devtools-components package (the
debugger does not use it yet though)

**Comment by jasonLaster** [comment]
@nchevobbe can i upgrade that w/o upgrading reps?

should i just wait for reps?

**Comment by nchevobbe** [comment]
There's is no specific fix in Reps for that, unless it uses the new
devtools-components package. I guess you could hack something on the
debugger to make your reps + source tree use it.

**Comment by nchevobbe** [comment]
closing as the debugger use latest devtools-components now
