### ISSUE TITLE
Tree component does not work w 15.6.2

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#733]
There's a child ref in the component that is breaking in 15.6.2

STR:

1. upgrade react to 15.6.2 in components
2. open `yarn storybook`

**Comment by yurydelendik** [comment]
The STR looks incomplete. I was not able to observe any bad behavior. Could you update STR to include more detailed steps and expected/actual behavior?

Blocks https://github.com/devtools-html/debugger.html/issues/4168

**Comment by nchevobbe** [comment]
closing since the debugger do use the latest devtools-components
