### ISSUE TITLE
New Tree component only expands on clicking the expander arrow

### ISSUE THREAD

**Issue by wldcordeiro** [devtools-html/devtools-core#734]
The old tree component had been made to expand its nodes on clicking the entire node rather than just the arrow as a UX nicety since the arrow is a tiny click target.

**Comment by nchevobbe** [comment]
Where do you see that Wellington ? In code, the listener is on the whole
tree node
https://github.com/devtools-html/devtools-core/blob/90ed1dd17fb27d0e23c62a2b864b07bcf48b2879/packages/devtools-components/src/tree.js#L132,
which is set here
https://github.com/devtools-html/devtools-core/blob/90ed1dd17fb27d0e23c62a2b864b07bcf48b2879/packages/devtools-components/src/tree.js#L753
. Do I miss something ?

Le 30 sept. 2017 22:53, "Wellington Cordeiro" <notifications@github.com> a
écrit :

**Comment by wldcordeiro** [comment]
@nchevobbe Come to think of it, it may be an issue with how the Debugger consumes it. That said, we did revert the change to the new tree over some other issue. 🙁 


https://github.com/jasonLaster/debugger.html/blob/73183b05dbe41b6ec84a9c98e3988c97c22aa3d3/src/components/PrimaryPanes/SourcesTree.js#L209

**Comment by nchevobbe** [comment]
closing since the component is successfully used in the debugger
