### ISSUE TITLE
Convert tree indent / border width / arrow width vars into js props instead of CSS variables

### ISSUE THREAD

**Issue by bgrins** [devtools-html/devtools-core#739]
The CSS rules that we generate in
https://github.com/devtools-html/devtools-core/blob/739e193ec48df0ca5d876deb14cd894775ae2f4d/packages/devtools-components/src/tree.js#L100-L114 cause time spent when inspecting a large object to be spent resolving the variable value: https://bugzilla.mozilla.org/show_bug.cgi?id=1405052#c3.

If we stored those in JS as props with default values as px instead of the default value we currently have in CSS then this should be a lot faster (https://github.com/devtools-html/devtools-core/blob/d09c9f5ec071b1093bed1d7cca44a065f152ddee/packages/devtools-components/src/tree.css#L10-L12).

Or, we could remove the border entirely

**Comment by nchevobbe** [comment]
done
