### ISSUE TITLE
[Mapping] we should map identifiers in an expression

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#741]
We currently map minified variables when the debugger pauses. We should try and map all of the identifies. Here's an example:

#### Minified

```js
function sum(n,u) {
  return n + u
}
```

#### Original source

```js
function sum(first, second) {
  return first + second;
}
```

We can currently map `n` to `first`, but if the user types in the console `first * 2`, we can't map it to `n * 2`. We can solve this by parsing the expression and looking for identifiers to map.

**Comment by jasonLaster** [comment]
here is a [test][t] 

[t]:https://github.com/devtools-html/devtools-core/compare/master...jasonLaster:mapping?expand=1

**Comment by aleksdao** [comment]
@jasonLaster We worked on this as part of the React NYC / FF Devtools Contribution night last week. Unfortunately, I was unable to submit a PR as I was having some issues with the pre-commit hook complaining about `yarn run lint`.

I went ahead and pushed up the code to my fork with `--no-verify`. Hope that's alright and won't cause any issues.

Should I create a PR for feedback? https://github.com/devtools-html/devtools-core/compare/master...aleksdao:feature/ast-mapping-identifiers?diff=unified&expand=1&name=feature%2Fast-mapping-identifiers

**Comment by jasonLaster** [comment]
Thanks @aleksdao! This looks great. Feel free to make a PR. If you're busy, someone else can as well!

**Comment by aleksdao** [comment]
@jasonLaster Great - thanks! I'll make a PR this evening... just didn't want to make a PR and waste everyone's time if it wasn't on the right track :)

**Comment by jasonLaster** [comment]
yep
