### ISSUE TITLE
Link opens at the end of the tabbar

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#760]
Open at least 2 tabs in a window, focus the left one, and enter this into the console:

    "http://example.com"

Click the resulting link. The new tab opens at the end of the tabbar instead of just at the right of the current tab.

**Comment by nchevobbe** [comment]
openLink is provided by the console, so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1457109 to deal with this
