### ISSUE TITLE
Allow to copy link location

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#761]
When I right-click a link in a web page, there is the "Copy Link Location" option.

But if I enter `"http://example.com"` into the console, I get "Copy message" and "Copy object".

"Copy message" seems to copy the string with quotes and with a trailing newline. "Copy object" seems to copy the string with quotes.

There should be some way to just copy the link location, without quotes.

**Comment by nchevobbe** [comment]
The context menu entry is handled by the console, so I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1457111 to fix this issue
