### ISSUE TITLE
Duplicate Scope Item

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#769]
We show the same item twice because `jQuery` has two property names `$` and `jQuery` each with the same displayName.

<img width="1137" alt="duplicatescope" src="https://user-images.githubusercontent.com/46655/30774197-5ad73f0c-a044-11e7-8b27-eab9d76ed30e.png">

**Comment by jasonLaster** [comment]
@hughugsy  is on it

**Comment by nchevobbe** [comment]
I think this is fixed now

**Comment by jasonLaster** [comment]
yep
