### ISSUE TITLE
Upgrade to ES6 classes and silence all warnings

### ISSUE THREAD

**Issue by MikeRatcliffe** [devtools-html/devtools-core#772]
We need to upgrade all of our components to ES6 classes as part of the path to using React 16.

createClass() is deprecated and it's replacement, createReactClass(), is only a temporary fix whereas ES6 classes are here to stay.

We have a [custom codemod](https://github.com/MikeRatcliffe/moz-codemod) that can perform the upgrade to ES6 classes so we need to run that and make any additional changes.

After we are using ES6 classes we can rebase pull request #770, which really is a great step forward.

**Comment by MikeRatcliffe** [comment]
It has been easiest to upgrade to ES6 classes and address warnings all in one go. Warnings do not only come from our code... they also come from submodules and their dependencies so I have had to upgrade a bunch of dependencies to silence all warnings.

My patch will stop just short of upgrading to React 16.

**Comment by MikeRatcliffe** [comment]
Enzyme was completely rewritten for Fibre so when we upgrade to react 16 somebody will need to fix all the tests or we can switch to another testing system.

Anyhow, no warnings and all ES6 classes.

**Comment by brutalcrozt** [comment]
It will remove warning about babel-preset-es* right?

**Comment by brutalcrozt** [comment]
@MikeRatcliffe this still open, is this still leaving some to do?
Sorry i just want to make sure :smile:
