### ISSUE TITLE
Opening Browser Toolbox causing: NS_ERROR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by wagnerand** [devtools-html/devtools-core#783]
STR:

1. Use Nightly 58
2. Open the Browser Toolbox

Expected results:

A functional Browser Toolbox window.

Actual result:

<img width="908" alt="screen shot 2017-11-06 at 17 50 23" src="https://user-images.githubusercontent.com/873258/32453038-84bf489c-c31b-11e7-9c34-2a456a7a0b42.png">

**Comment by jasonLaster** [comment]
the devtools: framework component

**Comment by nchevobbe** [comment]
@wagnerand , you can use https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Framework

**Comment by juliandescottes** [comment]
I don't think this is new to 58, I remember it happening occasionally on Nightly. For the record, quitting the toolbox and reopening it usually works for me.
