### ISSUE TITLE
Have a UI to filter properties on the ObjectInspector

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#803]
This was possible in the VariableView (even if wonky), and we could implement it for the ObjectInspector.

We should also take into account https://bugzilla.mozilla.org/show_bug.cgi?id=809391 to implement smart search.

**Comment by jasonLaster** [comment]
the `jq` tool is a good example too: https://stedolan.github.io/jq/tutorial/

**Comment by jasonLaster** [comment]
Lets do a brainstorming session w/ victoria

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6127
