### ISSUE TITLE
Unify <custom> nodes in the ObjectInspector

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#804]
From https://bugzilla.mozilla.org/show_bug.cgi?id=866877, about the variable view 

The current status quo of how to display non-property info is:

> There are pseudo-properties with names in angle brackets:
> - `<return>` and <exception> for return state of a function
> - `<Closure>` for function's environment bindings
> - `<state>`, `<value>` and `<reason>` for promise state
> - `<entries>` for Map/Set entries (you need to apply patch from bug 1172920 to see this)
> - `__proto__` is a "normal" property displayed always at the end of the property list
> 
> Various properties and pseudo-properties have names in different colors:
> - first, enumerable and non-enumerable properties are in a different shade of blue: non-enums are lighter, with opacity: 0.6
> - `<return>` is green, `<exception>` is red
> - `<Closure>` and its nested scopes are in green
> - promise's `<state>` is light blue, same as non-enum property
> - Map's `<entries>` are blue, same as enum property
> 
> Are the pseudo-properties displayed before, or after normal properties?
> - `<return>` and `<exception>` are always first
> - `<state>` and `<entries>` are also first (that makes sense, because it's arguably the most important information about the Promise or Map)
> - `<closure>` is displayed as last (that makes sense too, because it's not primary, but an auxiliary information about the function)
> 
> I think there are several inconsistencies that should be fixed:
> - lowercase labels should be used consistently. I.e. `<Closure>` should be `<closure>`
> - the `<state>` and `<entries>` shouldn't have different colors. And maybe they should have a color different from normal properties
> 

I don't think we have `<return>` and `<Closure>` (maybe we should add them), but we could have different colors and unify casing for those custom nodes

**Comment by Loirooriol** [comment]
Just for reference, there are more custom properties, like `<target>` and `<handler>` for [[ProxyTarget]] and [[ProxyHandler]], respectively. And there should be something for wrapped primitives (#708).

@nchevobbe You forgot to escape `<` and `>`, so github attempts to parse as HTML.

**Comment by nchevobbe** [comment]
Thanks @Loirooriol

**Comment by nchevobbe** [comment]
done in https://github.com/devtools-html/devtools-core/pull/982
