### ISSUE TITLE
[Reps] Object with 20,000 properties is slow

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#843]
GWT applications can have 20,000 member properties in the window object.

Here is a small test case that shows an array working, but an object failing:
https://large-objs.glitch.me/

CC @goldenPenguin http://github.com/devtools-html/debugger.html/issues/1492

> Hello, this issue is affecting me currently. I'm working on a project written in GWT that generates a lot of code (with sourcemap) and the window object can take up to 10-15 seconds to expand at each debug step-in/out/over (it re-expands every time). There is around 20000 members in the window object at the moment.

**Comment by Loirooriol** [comment]
See #608.

**Comment by jasonLaster** [comment]
Thanks @Loirooriol.

**Comment by jasonLaster** [comment]
Hey @GoldenPenguin stop by our slack

**Comment by GoldenPenguin** [comment]
Will do :).

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6119
