### ISSUE TITLE
Stop using unreliable isGrip

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#844]
The `isGrip` function is completely unreliable:

https://github.com/devtools-html/devtools-core/blob/e9238260b69412731d3f158444be5a10eb8f2658/packages/devtools-reps/src/reps/rep-utils.js#L15-L17

It should be removed in favor of the `noGrip` parameter.

Otherwise nasty bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1377668 may happen. Just fail fast and loud to detect what uses should pass `noGrip = true`, and otherwise assume it's a grip.

**Comment by nchevobbe** [comment]
This issue was moved to devtools-html/debugger.html#6118
