### ISSUE TITLE
Blank page when jumping to function created in console

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#862]
1. Open web console
2. Enter `(function(){})`
3. Click "Jump to definition"

Result:
 - Blank page opens
 - Browser console shows this error:
   NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebNavigation.loadURI]  [viewSource-content.js:331](https://searchfox.org/mozilla-central/rev/b1e0ae2573e88391a7ed92407568be77994c9317/toolkit/components/viewsource/content/viewSource-content.js#331)

I guess the url is `"debugger eval code"` and you should blacklist that and hide the button. https://searchfox.org/mozilla-central/search?q="debugger+eval+code"

Introduced in #640, https://bugzilla.mozilla.org/show_bug.cgi?id=1419479
Cc @nchevobbe

**Comment by nchevobbe** [comment]
Thanks for filing @Loirooriol .
Seems like we had this case covered in the old console https://searchfox.org/mozilla-central/source/devtools/client/webconsole/console-output.js#112-113 .

**Comment by Loirooriol** [comment]
While you are at it, in the old console `Function.prototype` was especially problematic ([bug 1297466](https://bugzilla.mozilla.org/show_bug.cgi?id=1297466)) because bizarrely it must be an interpreted function. It behaves well in the new console, but please add a test if there is none.

**Comment by nchevobbe** [comment]
There is a test, not specifically for `Function.prototype`, but for function grip with a `null` url, which is the case of `Function.prototype`.
