### ISSUE TITLE
Non-cropped URLs are not rendered

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#864]
```js
Rep({
  member: {"open": true},
  object: "http://example.com",
}).props.children;
```

Result: empty string
Expected: a link

Regressed by [bug 1419479](https://bugzilla.mozilla.org/show_bug.cgi?id=1419479), probably https://github.com/devtools-html/devtools-core/commit/e9238260b69412731d3f158444be5a10eb8f2658. Causes [bug 1426094](https://bugzilla.mozilla.org/show_bug.cgi?id=1426094).

Cc @nchevobbe

**Comment by nchevobbe** [comment]
Thanks @Loirooriol . I'll push a PR shortly, with a test for this case.

Eventually, we could get rid of this `member` prop and force consumer to only pass a falsy crop limit when they don't want a cropped string
