### ISSUE TITLE
getTitle should check noGrip

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#883]
```js
Rep({
  object: {class: "Array"},
  noGrip: true,
}).props.children[0].props.children
```

Result: `"Array"`
Expected: `"Object"`

Causes https://bugzilla.mozilla.org/show_bug.cgi?id=1428587

Just check `props.noGrip` and then use `DEFAULT_TITLE` or something like this.

**Comment by Loirooriol** [comment]
Well, in fact attempting to handle both grips and raw objects is a complete madness. I think it would be much more reliable to check `noGrip` only once and, if true, attempt to create a grip as close as possible to what object.js would do. And then all the following code can safely assume it's a grip.
@nchevobbe What do you think?

**Comment by nchevobbe** [comment]
This bug is fixed: 

![image](https://user-images.githubusercontent.com/578107/35961186-08961e36-0cad-11e8-93bb-12317e4d4cda.png)

**Comment by nchevobbe** [comment]
ignore my previous comment

**Comment by nchevobbe** [comment]
In fact, for now, I don't see any reason to check for the class property on the object.

**Comment by Loirooriol** [comment]
> In fact, for now, I don't see any reason to check for the class property on the object.

No, that's so important, e.g. if I have a dead object I want the console to show `DeadObject {  }` instead of `Object {}`.

**Comment by nchevobbe** [comment]
I agree, but this would be picked up by the Grip object I guess ? How can I test this DeadObject scenario ? We'd better have a test here for it as well

**Comment by Loirooriol** [comment]
I think the easiest way to obtain a dead object is running the following code in a privileged web console (like browser console or web console in an `about:config`):

```js
var s = Cu.Sandbox(null);
Cu.nukeSandbox(s);
s;
```

But there are also various other objects that don't have a specific grip or rep type, e.g. `getSelection()` produces a `Selection` object.

**Comment by nchevobbe** [comment]
Thanks for the tip @Loirooriol  :) 
So I was able to get a dead object, and the packet looks like the following: 
```json
{
  "type": "object",
  "actor": "server1.conn7.child2/obj41",
  "class": "DeadObject",
  "extensible": true,
  "frozen": false,
  "sealed": false
}
```

which renders as `DeadObject {  } ` with my patch on Object.js. I think (and I will assert that with a test), that the DeadObject is rendered with the `Grip` rep.

**Comment by nchevobbe** [comment]
Pushed https://github.com/devtools-html/devtools-core/pull/926 to deal with DeadObjects

**Comment by Loirooriol** [comment]
OK, I thought ObjectRep and GripRep were the same. Then I think it's OK.
