### ISSUE TITLE
Do not toggle object inspector nodes when selecting text

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#885]
1. Open the console
2. Enter `inspect({a: () => {}})`
```
▼ {…}
  ▶ a: function a()
​  ▶ __proto__: Object { … }
```
3. Select `fun`

Before you can e.g. copy it, the property is expanded and `fun` disappears:
```
▼ {…}
  ▼ a: a()
     length: 0
     name: "a"
​  ▶ __proto__: Object { … }
```

**Comment by nchevobbe** [comment]
@weilonge this might be a good one to work on if you plan to contribute here :)

**Comment by weilonge** [comment]
@nchevobbe  Does this mean that there should be the string "function" in "a: a()"? Like this?
▼ {…}
  ▼ a: **function** a()
     length: 0
     name: "a"
​  ▶ __proto__: Object { … }

**Comment by nchevobbe** [comment]
@weilonge not really, it means that in https://github.com/devtools-html/devtools-core/blob/b39a79d112b2c99b800e2ad33f1c611904de9cdc/packages/devtools-reps/src/object-inspector/index.js#L369, if we have a text selection going on, we should not call `setExpanded` (https://github.com/devtools-html/devtools-core/blob/b39a79d112b2c99b800e2ad33f1c611904de9cdc/packages/devtools-reps/src/object-inspector/index.js#L372).

And somehow make a test to make sure we don't regress that.
You can reproduce the bug with the Reps test app (`cd packages/devtools-reps && yarn && yarn start`)

**Comment by Loirooriol** [comment]
I was thinking something like

```js
if (getSelection().isCollapsed) {
  // toggle node
} else {
  // do nothing
}
```
