### ISSUE TITLE
npm start fail due to devtools-launchpad webpack config

### ISSUE THREAD

**Issue by gasolin** [devtools-html/devtools-core#89]
Reproduce step:

1. run command `node bin/dev-server.js` in `https://github.com/devtools-html/devtools-reps`

It shows error
```
webpackConfig.entry.bundle.push("webpack-hot-middleware/client")
                                            ^
TypeError: Cannot read property 'push' of undefine
```

possible fix:

To run dev-server properly, I add default 
```
entry {
  bundle: []
}
```
to prevent `undefined` issue.

```
if (getValue("hotReloading")) {
  + webpackConfig.entry = webpackConfig.entry || {};
  + webpackConfig.entry.bundle = webpackConfig.entry.bundle || [];
   webpackConfig.entry.bundle.push("webpack-hot-middleware/client");
   ...
```

After patch I can see http://localhost:8000/ without error, but it still shows blank page though

**Comment by wldcordeiro** [comment]
@gasolin What version of Node.js and OS are you using? I haven't seen this issue myself and some platform info might be good.

**Comment by gasolin** [comment]
Node 6.9.1 on Elemntary OS (ubuntu 14.04 varient), 

download dependencies with normal `git clone` devtools-rep git, `npm install`
