### ISSUE TITLE
Devtools freezing and unusable 

### ISSUE THREAD

**Issue by chrisjasp** [devtools-html/devtools-core#902]
I have multiple applications that I use dev tools for. They all use Webpack and sourcemaps. I'm not exactly sure what causes the issues but I am unable to use devtools at all. The pages work fine when tools are not open. As soon as I open the dev tools, links, buttons, anything on the screen is completely frozen. I can navigate around in dev tools but I cannot use the Web App anymore. There are a couple of warnings related to Unreachable code after return but no errors in the console. I would love to get this resolved so I don't have to use other browsers when I'm developing. I can provide answers to any questions you have. Sorry for the lack of details but I'm not sure what more I can provide at this point.

**Comment by nchevobbe** [comment]
Hello  @chrisjasp ! 
This repo is for small packages that are used by devtools, so issues would be better handled on [Bugzilla](https://bugzilla.mozilla.org) (on which you can log on with a Github account).
We also have a discourse, where some people already shared their slowness and where we do respond as well (see https://discourse.mozilla.org/t/devtools-slow-and-occasionally-unresponsive-on-some-sites/19936/16).

---

About the slowness now, what version are you using ? If you're not on Nightly, can you try it and tell us if it is any better ?
Last way you can help is by recording and uploading a profile using http://perf-html.io/, which would give us hints of what your slownesses are.
Also, is the application being frozen public ? Or is there a way for us to access it and investigate against it ?

Thanks !

**Comment by chrisjasp** [comment]
I'm not actually experiencing any slowness. It it completely freezing and unusable like I originally said. I will close the issue and report it to the proper place. Thank you for your feedback.

**Comment by nchevobbe** [comment]
@chrisjasp what do you mean by "frozen" ? What panel are you trying to use ? Could it be that there is a `debugger;` statement somewhere in your code ?

**Comment by chrisjasp** [comment]
This happens across several applications. The common thing between them is webpack. I confirmed there are no debugger statements. It happens across multiple panels. The only other consistent thing I can come up with is that if the last console output happens to be a warning, that is when it seems to happen. If it is just info in the console it seems to be okay until a warning comes up. The warnings I see are related to unreachable code after return statement. I don't get this warning in other browsers running the same code incidentally.
