### ISSUE TITLE
[tree] detect itemHeight

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#908]
The tree component assumes `itemHeight` will be passed in. The problem is that the height often changes and is then wrong.

It would be great if the tree could calculate the `itemHeight` when it mounts.

**Comment by nchevobbe** [comment]
we don't have itemHeight anymore.
It was used to do some virtualization but wasn't used.
What is the original issue ?

**Comment by jasonLaster** [comment]
that the heights are not accurate when you scroll because we were using the wrong value for itemHeight :)

**Comment by nchevobbe** [comment]
I am pretty sure we  do not set the height of elements on the Tree component.
Here's how we handle scrolling : 

https://github.com/devtools-html/devtools-core/blob/57edbf8992acf55661e2b8c0faf144dd3b89c9e5/packages/devtools-components/src/tree.js#L548-L578

**Comment by nchevobbe** [comment]
Closing this as INVALID, feel free to re-open it if you think I'm wrong :)
