### ISSUE TITLE
[Tree] weird scroll behavior

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#914]
The tree has a funny scroll behavior with up and down arrows

http://g.recordit.co/qAO0ndrlwT.gif

**Comment by nchevobbe** [comment]
@jasonLaster do you have an STR for this ?

**Comment by jasonLaster** [comment]
Yep, 

1. pause 
2. expand window
3. click on a node
4. use up/down arrows

**Comment by nchevobbe** [comment]
great, thanks !
