### ISSUE TITLE
We should be able to expand longStrings in the ObjectInspector

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#941]
**Steps to reproduce**
1. Evaluate `({long: "ab ".repeat(10000)})`

**Expected results**
I can expand the `long` property to see the whole string content

**Actual results**

I don't have any way to see the whole string content

---

@kootoopas I am assigning this to you since you started to work in it in another PR, but feel free to not take it if you don't want to/don't have the time :)

**Comment by kootoopas** [comment]
Oh hey @nchevobbe. Cool, I'm currently working on this anyway. :)

How do you think it's the best way to expand it?
* The clickable existing trailing ellipsis option seems that it can go unnoticed to me.
* If we were to make the whole string rep clickable, wouldn't that be an overkill?
* I like the idea of an expand button at the end of the string... Maybe label it with `…` and remove the existing in-string trailing ellipsis?

**Comment by nchevobbe** [comment]
So, I think we should align with what we are doing in the json viewer: if you go to [this URL](data:application/json,{"string":"aaa","longString":"aaaaaasdfsdfsdolijfsdklfjsdlkfjsdlfkjsdflksdjflskdjfsdlkjfsdlkjfhsdkjfhsdkjfhdfkgjhdfkgjhdfkgjhdfgkjdfhgkdfjhgkdf"}), you'll see that you can collapse the "longString" property, and re-expand it.
I think it should behave the same in the ObjectInspector so we are consistent.

Anything that would be placed at the end of the string can be unnoticed I think, and I like the idea of a consistent way to expand a node. What do you think ?

**Comment by kootoopas** [comment]
I prefer the consistent approach too. I didn't think about checking out the json viewer at all!

So, If I understand correctly:
* prepend a togglable arrow
* abbreviate the string as in the json viewer
* style the abbreviated string, if it's a standalone string, or property key, if it's an object property, like a link (pointer & underline)

**Comment by nchevobbe** [comment]
Fixed by https://github.com/devtools-html/devtools-core/pull/1015
