### ISSUE TITLE
Consider adding better snapshots to reps

### ISSUE THREAD

**Issue by gregtatum** [devtools-html/devtools-core#943]
There are nicer formatters for snapshots available, and would help the testing assertions for reps. This takes an enzyme wrapper, and renders it as a nice DOM tree string representation. I took a quick stab at adding this with #942 but got bogged down in the upgrades.

https://www.npmjs.com/package/enzyme-to-json

We would need to upgrade Jest and Enzyme in order to get this.

**Comment by jasonLaster** [comment]
Thanks for starting this and sharing :)

**Comment by nchevobbe** [comment]
I'll do this when reduxification of the objectInspector is over

**Comment by nchevobbe** [comment]
doable after https://github.com/devtools-html/devtools-core/pull/966 lands
