### ISSUE TITLE
Upgrade to webpack 2

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/devtools-core#96]
Webpack 2 will help us in many concrete ways
* linking will not have duplicate files
* builds will be deterministic and more reliable

The migration guide lays out the steps, which seem very doable
https://webpack.js.org/guides/migrating/

**Comment by wldcordeiro** [comment]
I'm going to take a stab at this, I've been meaning to get a better understanding of Webpack so it isn't so much of a black box to me. 😆

**Comment by nchevobbe** [comment]
webpack 4.0.0 just went out. Let's close this and file a new issue for the update to 4.0.0

**Comment by jasonLaster** [comment]
haha - yeah, but we're also on 3 now which will help
