### ISSUE TITLE
Add a <closure> node in the ObjectInspector

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-core#984]
This was done in the VariableView before (https://searchfox.org/mozilla-central/rev/9bab9dc5a9472e3c163ab279847d2249322c206e/devtools/client/shared/widgets/VariablesViewController.jsm#440-481)

**Comment by nchevobbe** [comment]
@jasonLaster do you think this is useful ?
It seems to me that it can only be shown when the debugger is paused (trying to fetch the scope gave me `"cannot access the environment of this function."` from the server).

And in that case, if you want to inspect a value, it should be in the scopes panel. Is there something I'm missing here ?

**Comment by jasonLaster** [comment]
hmm, it should work at any time in theory. Lets check with @jimblandy.

**Comment by nchevobbe** [comment]
Not a priority right now. Let's reconsider it later
