### ISSUE TITLE
Replace Object.assign with spread properties

### ISSUE THREAD

**Issue by Loirooriol** [devtools-html/devtools-core#986]
`Object.assign({}, obj)` is used all over the place. But this calls setters!

This is harmful in case `obj` contains an own `__proto__` property.

You should use `{...obj}` ([spread properties](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/Object_initializer#Spread_properties)) instead. Compare:

```js
let obj = {["__proto__"]: null};
Reflect.ownKeys(Object.assign({}, obj)); // []
Reflect.ownKeys({...obj});               // ["__proto__"]
```

Specifically in https://github.com/devtools-html/devtools-core/blob/b6aa4ab9787d519c9f468af91f4755760a9265b1/packages/devtools-reps/src/reps/grip.js#L156

it's the cause of [bug 1390027](https://bugzilla.mozilla.org/show_bug.cgi?id=1390027).

**Comment by jasonLaster** [comment]
Great find @Loirooriol!
