### ISSUE TITLE
Switch to CSS SVGs

### ISSUE THREAD

**Issue by AnshulMalik** [devtools-html/devtools-core#988]
Referencing https://github.com/devtools-html/debugger.html/issues/4350

We would like to switch from using react-based inline SVGs to CSS-based SVGs. The primary advantage is performance. SVGs created by React are slow to render. CSS drawn SVGs have a significant perf benefit.

TODO:
- [ ] convert Object Inspector arrows
- [ ] convert "Open in inspector" icon
- [ ] convert "Jump to definition" icon

**Comment by nchevobbe** [comment]
Added some cases to the TODO list. Thanks @AnshulMalik  for starting this
