### ISSUE TITLE
Timeline in Network tab is too narrow and not resizable

### ISSUE THREAD

**Issue by phanect** [devtools-html/devtools-core#999]
# Step to Reproduce

1. Show Firefox on display which is smaller than 15 inch.
2. Open Firefox DevTools (Ctrl+Shift+I)
3. Open Network tab
4. Go to any web page so water fall chart is shown.

# Actual Results

Timeline is too narrow and colored bars are not visible.
I cannot resize timeline either.

![Firefox's Timeline](https://user-images.githubusercontent.com/315601/37556157-324a738a-2a35-11e8-946e-8cf10240f67d.png)

# Expected Results

Users can resize width of timeline, like Chrome/Chromium's water fall chart.
![Chrome's Water Fall Chart](https://user-images.githubusercontent.com/315601/37556162-4e7126f8-2a35-11e8-8302-3e9498d09afd.png)

**Comment by janodvarko** [comment]
Thanks for the report!

Yes, this is known issue tracked by this bugzilla bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1358414

Honza

**Comment by phanect** [comment]
Oh I wasn't noticed for the issue. Sorry! :bowing_man:
